### ISSUE TITLE
Images are lost after update

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/homeslider#3]
I have updated this module now twice this week. In both cases my slider images were gone. They don't show up in backoffice and also not in front office.

It could be related to multistore!? TB Version is 1.0.3.

For the themconfigurator I noted the same problem...

**Comment by Dh42** [comment]
It seems to happen on the standard non multi-store as well. I just got a report about it in my support queue.

**Comment by Traumflug** [comment]
It smells a bit like an somehow changed update process. Code changes of the last two releases are limited to pretty much comment and whitespace edits. Now I wonder why these images did *not* go with earlier releases.

**Comment by eschiendorfer** [comment]
I believe, they did get lost already before. When I migrated, I had the same issue. Back then, I thought it was because of the migration process... Now I know it better ofc.

**Comment by selwynorren** [comment]
Same thing happened to me. I logged into my admin interface and had a whole bunch of modules that needed updating. I updated them all and all my images for these module have all been deleted from the server. This specific homeslider module no all of a sudden has css not in another location where it never was before, which means my theme is not applying the styles at all

**Comment by Traumflug** [comment]
> This specific homeslider module no all of a sudden has css not in another location where it never was before, which means my theme is not applying the styles at all

Obviously a result of the new packaging script, which no longer forgets one file or another.

CSS files in the theme override those in the module, so creating an empty file `themes/<theme>/css/modules/homeslider/<file>.css` should solve the issue (and won't get overwritten with the next module upgrade either).

**Comment by Dh42** [comment]
I tested this, the only thing I can come up with is a permissions issue on the /images directory that caused the issue. I added a build script and tested an upgrade from the current version to the new version and did not have the issue. I am closing this for now and making a new release.

**Comment by eschiendorfer** [comment]
I am not sure, if it's good to close this one. I just updated theme configurator from 3.0.6. to 3.0.7 and lost again the images. I believe there is some issue left...

**Comment by Traumflug** [comment]
Proposed solution: don't store these images in the module folder. Images go to `img/`. Those in the module folder are only templates and should get copied to `img/homeslider/` on installation. Front end HTML should expect them there.

Reason: when updater updates a module, it removes the entire directory, then unpacks the new release. Accordingly, all files inside the module folder are gone.

**Comment by selwynorren** [comment]
> Proposed solution: don't store these images in the module folder. Images go to `img/`. Those in the module folder are only templates and should get copied to `img/homeslider/` on installation. Front end HTML should expect them there.
> 
> Reason: when updater updates a module, it removes the entire directory, then unpacks the new release. Accordingly, all files inside the module folder are gone.

This would be an awesome solution, It gets pretty irritating when each time an update runs, then we have to re-upload the images again, Love this way of handling the images

**Comment by selwynorren** [comment]
Just a heads up to anyone. With the new changes, it never backups or transferred my images to the new location and I lost everything again... Fortunately I still have my backups
