### ISSUE TITLE
Non-JS compatibility

### ISSUE THREAD

**Issue by gstesq** [thirtybees/homeslider#4]
The slider doesn't seem to generate a static image like the PS1.6 slider does when JS is disabled . All images that were contained within the slider are displayed across the page, which is not pretty.

**Comment by Traumflug** [comment]
I think we can close this issue. thirty bees doesn't work without JavaScript, e.g. these buttons in the cart to add or remove products and recalculating their prices make heavy use of it. Same for all the Ajax requests.
