### ISSUE TITLE
Images Fails to Load

### ISSUE THREAD

**Issue by folliejester** [thirtybees/homeslider#7]
The images in slider loads in live page after setup
The images in slider do not load after being replaced with new images

Tried : using png jpg jpeg and gif image formats

**Comment by getdatakick** [comment]
What version are you using? 

This is probably related to update to latest version of the module. Your theme might need to be updated, if it contains template override. See this comment: 

https://forum.thirtybees.com/topic/6050-solved-module-block-image-slider-wrong-img-dir/?do=findComment&comment=45773
